### ISSUE TITLE
snv not inserted on reads with snv close-by

### ISSUE THREAD

**Issue by tdelcourt** [adamewing/bamsurgeon#123]
I try to insert two snv close-by but i see that only the second one is correctly inserted. The first one is not inserted on the reads that also cover the second position. (cf image)

I found a work-around by setting the haplosize to > reads length (250), which works well if inserting at VAF 100% but would probably cause problems for lower VAFs.

Am I missing something? Is there an option that would allow this differently? Is this a bug?
It may be related to [https://github.com/adamewing/bamsurgeon/issues/40](https://github.com/adamewing/bamsurgeon/issues/40)

![missing snv](https://user-images.githubusercontent.com/7101984/48132191-f5b23680-e292-11e8-9f71-195f8b6c6368.png)

**Comment by adamewing** [comment]
That's exactly the situation the "haplosize" argument is designed to address. It should work fine with VAF < 1.0 but the linked SNPs will have the same VAF in the output.

The reason behind this is mutations are generated independently by default, so if two mutations share reads because they're close together one of them will be lost (or decreased on VAF) in the final merge step. Using `-z` makes addsnv more haplotype aware by identifying snps that are likely to share reads and modifying the reads once for all snps on a haplotype group.

**Comment by tdelcourt** [comment]
Yes, I assumed the final merge was the reason.
If it ever was a problem, I guess successive passes of bamsurgeon for each individual mutation would be ok, if halpotypes were to be completely ignored.

Thanks for the answer,

thomas
