### ISSUE TITLE
DEL format of varfile for addsv.py

### ISSUE THREAD

**Issue by codeunsolved** [adamewing/bamsurgeon#126]
Hi,

Here I want to simulate some SVs by `addsv.py`, for example, DEL.

Sorry for my stupidity. After reading manual multiple times, I still don't understand how to fill 5th and 6th columns of DEL in varfile.

>22 33871043 33884754 DEL 0.9 0.75
>
> For deletions, DEL should be followed by the fraction of the largest contig to be deleted, where 1.0 indicates a deletion of the largest assembled region minus one library length on each end. e.g. DEL 0.5. This is optionally followed by specifying the per-mutation VAF (0.75 in the example above).

1). Is that means 6th column is VAF? And it is optional? How could it be optional?
2). What about 5th column? Is that the fraction of reads that in the range of library length(discordant insert size?) at two breakpoints?

Version: 1.1 (from release)

**Comment by adamewing** [comment]
Hi, sorry about the syntax. For version 1.1, column 5 indicates the fraction of the assembled contig that will be deleted. I would recommend keeping this at 1.0. This syntax has been removed as of [c1af4aa](https://github.com/adamewing/bamsurgeon/commit/c1af4aa924559199ff6f966ef7f9511005b414d6) and will be absent from 1.2, but is still present in the 1.1 release version.

Column 6 is the VAF, yes. It can be optional because it it's omitted, the default value set by the `-s/--svfrac` option to `addsv.py`.

Let me know if that doesn't answer your question(s).

**Comment by codeunsolved** [comment]
Thanks! @adamewing. Your answer gives me a better understanding of these parameters.
Your project is great!
