### ISSUE TITLE
no mate for...

### ISSUE THREAD

**Issue by krishdb38** [adamewing/bamsurgeon#157]
Hello, I am new in Genome Data Analysis.
I am trying to make an artificial mutation in my bam file like 

chr1	27022960	27022970 0.50 DEL
chr1	27023107	27023118 0.2 INS CA
chr1	27023446	27023446 0.3 DEL
chr6	157099040	157099050 0.4 DEL
chr6	157099050	157099055 0.4 INS ATGGC
chr6	157099150	157099155 1.0 INS GA
chr6	157099200	157099201 1.0 DEL

I am regularly seeing warning `no mate for... ` 
I also tried option  -- mindepth 3  (various low like 1 5 ..)
                               --minmutreads 3 (also different parameters... )

![Error1](https://user-images.githubusercontent.com/45994360/80930853-1b20f180-8df1-11ea-850b-54dfcf5885ca.PNG)

![igv](https://user-images.githubusercontent.com/45994360/80930874-4acff980-8df1-11ea-896f-b6c2d80d206a.PNG)

Your test file is running very well and in my file some where creating mutations and some where not.
Is there any suggestion please recommend me . 

Thank you Bamsurgeon is a good tool

Krish

![Error1](https://user-images.githubusercontent.com/45994360/80930911-8965b400-8df1-11ea-8057-67c3f1a40deb.PNG)

**Comment by adamewing** [comment]
Apologies for the rather long delay - I've been out on leave. The "no mate" messages are due to having a .bam file with paired end reads but in these instances only one end of the pair is present. Is your data paired end sequencing? If it's not, you can use the `--single` option. If it is and you're using a slice of the .bam file you could try using a larger slice or you can try using a script included in the `scripts` directory called `remove_unpaired.py` (this may not always work well).

**Comment by Rapsssito** [comment]
Closed due to inactivity.
