### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by joys8998** [adamewing/bamsurgeon#179]
Hi there, I'm trying to install you tool into my ububtu20.04 machine.
I followed the README instructions but I'm facing some error/differences:
1) During the installation of samtools, I have no `samtools/samtools` directory after the `git` and `make` commands. I have only `samtools/samtools.h` file into the `samtools`dir. Do I need to copy it into $HOME/bin? My samtools version is 1.10 while htslib is 1.10.2-3
2) During the installation of samtools I have no `samtools/misc/wgsim` dir but `samtools/misc/wgsim.1`and `samtools/misc/wgsim.c` files. Which one do I need to copy into $HOME/bin?
3) Exonerate installation fails because of a fatal error in the execution of the command `./configure && make && make check && make install`. The error is `In file included from fsm.test.c:17:
fsm.h:24:10: fatal error: glib.h: No such file or directory
   24 | #include <glib.h> /* For CHAR_BIT */
      |          ^~~~~~~~
compilation terminated.` What can I do to fix it?
4) Do I need to copy some file from exonerate folder?

Thanks for your help

**Comment by adamewing** [comment]
Sorry this reply is coming a bit late, in case this issue is still relevant to you:

1. and 2. you should copy the executable file somewhere within your `$PATH`. If you're building samtools yourself, and it built properly, there _should_ be an executable file called "samtools" in the samtools directory. Note there's also more than one way to go about installing these dependiencies, something like `conda install -c bioconda samtools` might work better for you if you're using miniconda/anaconda.

3. Make sure the glib development package is installed for your OS. This will depend on your specific system configuration but if, for example, it's Ubuntu then something like `sudo apt-get install libglib2.0-dev` could work. You might need to get a sysadmin involved if you don't have root/sudo access on your system.

4. Once you get it to build, you'll need the executable `exonerate` to be in your $PATH.

**Comment by Rapsssito** [comment]
Closed due to inactivity
