### ISSUE TITLE
Intermediate haplo BAMs not being generated

### ISSUE THREAD

**Issue by ShadrielleE** [adamewing/bamsurgeon#85]
Hey Adam,

I am running into a scenario where if I spike in a lot of mutations (e.g. >100 SNVs) into a BAM file, some of the intermediate BAMs don't get generated. For each mutation, it will generate a haplo_${chr}_${pos}_${pos}.tmpbam... but sometimes it doesn't. I'm actually tracking one of my simulations right now as it is running, and I am seeing missing intermediate BAMs as the mutations are being processed. As a result, they don't get merged in the final BAM.

I checked the logs and it is reporting as usual
creating tmp bam: ...
picked ...
wrote: ... mutated...
mapping
pairing
sam
sorting indexing
etc.

Coverage shouldn't be an issue as # reads tend to vary from 5 to >50, (and I'm actually using minimum reads to be 1). I've also set VAF to 1.0

Have you run into this problem before? Any insights would be helpful.
Thanks!

**Comment by adamewing** [comment]
Hi Shadrielle,

Are these mutations where you're not seeing the intermediates included the truth file (generated via makevcf*.py)? You're using --skipmerge to keep the intermediates, right?

**Comment by ShadrielleE** [comment]
Hi Adam,

I'm actually not using the --skipmerge option, the BAMs are generated as the mutations were being processed by addsnv.py. When all the mutations in the file are processed, these haplo bams get merged together with the original BAM. I do use makevcf*.py to generate the truth files, and those mutations that were missing the haplo BAMs were not present in the VCFs (as expected).

**Comment by adamewing** [comment]
OK, so when you say "haplo BAM" are you referring to one of the intermediates (i.e. one mutation or one set of haplotype-linked mutations per BAM) which are all merged into a final "donor" BAM before the reads are swapped out into the original BAM, or something else? Put another way, is there one variant file (-v) per haplo BAM is it one mutation per haplo BAM? Sorry, just trying to make sure I understand which file you're referring to.

Regarding chasing down the reason for a dropped mutation, have you tried making a variant file with just the dropped variant(s) in it and checking whether BS complains about anything in the stdout/stderr?

**Comment by ShadrielleE** [comment]
I have one variant file (-v) with X mutations to spike in, where a small subset seem to be missing. Here's a sample command I'm using:
addsnv.py -v mutations.txt -f file.bam -r ref.fa -o newfile.bam -n X -p 4 --tmpdir temp_dir/ --mindepth 1 --ignoresnps

I've tried what you suggested, only spiking the dropped variants into the BAM. I've tracked the issue in the code (addsnv.py ~line 428)
    print "Debug, haploclusters:" + str(haploclusters)

    for hc in haploclusters:
        # make mutation (submit job to thread pool)
        result = pool.apply_async(makemut, [args, hc, avoid, alignopts])
        results.append(result)

For these dropped variants, if I print result.get(), it gives me None. Another step closer into the code, and I've figured out the issue! It will only merge tmpbams if coverage difference passes the (default 0.9) "coverdiff" parameter, and for these dropped variants, they weren't passing it. One way to get around that was use "--force", I tried using that, and now it works.

Could you shed some light on why coverage IN and OUT may differ by > 10%? One I can think of is that the reads are aligning better elsewhere. Some numbers I'm seeing:
154 -> 129
141 -> 85
48 -> 26

Thanks again Adam

**Comment by adamewing** [comment]
Hi, sorry for the delayed response. You should also see warnings about incover > outcover if this is happening. When I see this happening it's usually due to a site where the alteration of a base leads to a better mapping somewhere else in the genome. This is especially the case in regions with poor mappability to begin with. One way to verify whether this is happening is to run it with --skipmerge, grab the read names from a log file of a mutation with incover > outcover, and locate the reads in the pre-merge donor BAM. If you see them going to multiple locations not corresponding to the intended mutation site you can verify that the new mapping (with the altered base) leads to a better mapping via BLAT or similar. If that is indeed what is happening, I generally don't make an effort to correct it as this is what would happen with a "real" mutation as well given the same mapping procedure, if that makes sense... Anyway I'm happy to help track down specific mutations if you like.

--Adam

**Comment by ShadrielleE** [comment]
Yep that makes sense Adam. Thanks for your help!
