### ISSUE TITLE
Deletions position

### ISSUE THREAD

**Issue by iranmdl** [adamewing/bamsurgeon#98]
Hi there,
I'm having an issue when inserting deletions into the reference. Let me explain the situation:
I have created the following deletion:

`5	112175533	112175534	0.908	DEL`

If I understood correctly the manual, for this case, the base located at position 112175533 is the one that is going to be deleted.

I've modified the genome with the deletion and then I've run `makevcfindel.py` to check if it has been successfully added:

`5	112175533	.	AA	A	100	PASS	SOMATIC	GT	0/1`

Then, I performed variant calling analysis to check if I'm able to detect the deletion.

`5	112175532	.	TA	T`

So yes, I'm detecting the deletion but I have to substract one base from the original deletion position  since according  to the VCF format it is reported the previous base. So.. I would suggest to consider this fact in the `makevcfindel.py` script.

The problem is that for some other deletions, the position reported in my VCF file is the same as in the input file. Example:

Input deletion:
`8	61654689	61654690	0.092	DEL`

(61654689 base deletion)

`makevcfindel.py`:
`8	61654689	.	GC	G	100	PASS	SOMATIC	GT	0/1`

Variant calling:
`8	61654689	.	GC	G`

So in this case I don't have to subtract one base pair from the start position... If we look at the BAM files (see images), we can see that for the second deletion, "8	61654689", the base deleted is actually the 61654690, not the 61654689, that's why we don't have to subtract one bp from the reported position...

Am I missing something?
Thank you in advance,

<img width="288" alt="screen shot 2017-10-16 at 13 49 51" src="https://user-images.githubusercontent.com/9413990/31611774-b3b84c74-b27d-11e7-8e06-a56e199b957b.png">
<img width="358" alt="screen shot 2017-10-16 at 13 49 24" src="https://user-images.githubusercontent.com/9413990/31611816-cdd62252-b27d-11e7-893e-617bd0b6a342.png">

**Comment by adamewing** [comment]
Hi,

Regarding the first issue (variant callers vs. makevcfindel.py output):

Most variant callers will [left-align variant calls](https://genome.sph.umich.edu/wiki/Variant_Normalization), but the script that comes with bamsurgeon doesn't, so you'll need to use a tool like GATK [LeftAlignAndTrimVariants](https://software.broadinstitute.org/gatk/gatkdocs/3.6-0/org_broadinstitute_gatk_tools_walkers_variantutils_LeftAlignAndTrimVariants.php) on the VCF generated by the makevcfindel script. I suspect that will explain the first discrepancy. Let me know if it doesn't.

Now the second issue (IGV vs. VCF variant calls):

[IGV is 0-based](https://software.broadinstitute.org/software/igv/IGV), while VCF is 1-based... for what this means in case you haven't had to deal with this mess before, the best explanation I've seen is here: https://www.biostars.org/p/84686/

To double check me on this (because I often mess this up), try loading the left-aligned VCFs into IGV along with the BAM to make sure the variant position lines up with the deletion in the reads.

Hope this helps!

--Adam

**Comment by adamewing** [comment]
Closing, feel free to reopen if there are still unresolved issues.
